# Generated by Django 5.2 on 2025-05-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20250503_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_attempt', 'Login Attempt'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified'), ('logout', 'Logout'), ('profile_updated', 'Profile Updated'), ('mfa_setup_started', 'MFA Setup Started'), ('mfa_verified', 'MFA Verified'), ('mfa_login', 'MFA Login'), ('signup_successful', 'Signup Successful'), ('user_temp_blocked', 'User Temporarily Blocked'), ('user_permanently_blocked', 'User Permanently Blocked'), ('ip_blocked', 'IP Blocked'), ('rate_limit_triggered', 'Rate Limit Triggered')], max_length=100),
        ),
        migrations.AlterField(
            model_name='signupattempts',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('email_already_exists', 'Email already exists'), ('blocked_ip', 'IP address is blocked'), ('rate_limited', 'Rate limited'), ('password_too_weak', 'Password too weak'), ('mismatched_passwords', 'Passwords do not match'), ('unknown', 'Unknown error')], max_length=50, null=True),
        ),
    ]
